//! ClarityOS kernel build script (Zig 0.13+).
//!
//! Produces a freestanding x86_64 ELF kernel that the bootloader can
//! load. Uses our custom linker script (boot/linker.ld) and the
//! bootstrap assembly in boot/start.S.
//!
//!     zig build              # build kernel/ at zig-out/bin/clarity-kernel
//!     zig build run          # build + boot under QEMU (requires qemu-system-x86_64)

const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.resolveTargetQuery(.{
        .cpu_arch = .x86_64,
        .os_tag = .freestanding,
        .abi = .none,
        .cpu_features_sub = std.Target.x86.featureSet(&.{
            .mmx, .sse, .sse2, .avx, .avx2,
        }),
        .cpu_features_add = std.Target.x86.featureSet(&.{
            .soft_float,
        }),
    });
    const optimize = b.standardOptimizeOption(.{});

    const kernel = b.addExecutable(.{
        .name = "clarity-kernel",
        .root_source_file = b.path("main.zig"),
        .target = target,
        .optimize = optimize,
        .code_model = .kernel,
    });
    // No red zone. On x86-64 SysV a leaf function may use the 128 bytes
    // below %rsp without adjusting it — but an interrupt taken at the same
    // privilege level pushes its frame at %rsp, straight through that area.
    // It cost nothing while no interrupt ever arrived; with the timer running
    // it is silent corruption of whichever leaf function was unlucky.
    kernel.root_module.red_zone = false;

    kernel.setLinkerScript(b.path("boot/linker.ld"));
    kernel.addAssemblyFile(b.path("boot/start.S"));
    kernel.addAssemblyFile(b.path("arch/x86_64/context.S"));
    kernel.entry = .{ .symbol_name = "_start" };

    // ── the first user program ──────────────────────────
    //
    // Built as its own freestanding executable and embedded in the kernel
    // image, rather than assembled byte by byte inside the kernel as it was
    // before. A linker's output is what the loader will actually meet:
    // several PT_LOADs with different permissions, and a .bss whose p_memsz
    // exceeds its p_filesz. None of that was exercised by one hand-made
    // segment.
    //
    // It rides in the kernel image because the physical memory allocator
    // already reserves that; a GRUB module would land somewhere pmm is free
    // to hand out, which is a separate problem to solve properly.
    //
    // Unlike the kernel, this target keeps SSE and does not use soft_float.
    // The kernel gives them up on purpose — an interrupt handler that never
    // touches a vector register can never be the thing that clobbers one —
    // but userspace is where floating point actually happens: a compiled
    // Clarity program is C, and C on x86-64 passes and returns every double
    // in xmm0. The kernel enables SSE for ring 3 (arch/x86_64/fpu.zig) and
    // carries the state across a context switch (arch/x86_64/context.S), so
    // there is nothing left for this target to work around.
    const user_target = b.resolveTargetQuery(.{
        .cpu_arch = .x86_64,
        .os_tag = .freestanding,
        .abi = .none,
    });
    const init_prog = b.addExecutable(.{
        .name = "clarity-init",
        .root_source_file = b.path("user/init.zig"),
        .target = user_target,
        .optimize = .ReleaseSmall,
    });
    init_prog.setLinkerScript(b.path("user/user.ld"));
    init_prog.entry = .{ .symbol_name = "_start" };
    init_prog.pie = false;

    // Hands the built ELF to the kernel as an embeddable file. getEmittedBin
    // also makes the kernel depend on it, so it is built first.
    kernel.root_module.addAnonymousImport("init_elf", .{
        .root_source_file = init_prog.getEmittedBin(),
    });

    // ── /bin/clarity-demo: a Clarity program ────────────
    //
    // The C is generated by `clarity cc --freestanding` and checked in as
    // user/clarity_demo.c, because this build has to work with only Zig
    // installed — the OS-boot job has no bun and no Clarity compiler, and
    // making it fetch one to build a kernel would tie booting the OS to a
    // network. stdlib/test_libc.clarity regenerates the file and fails if it
    // has drifted, which is the check that keeps the artifact honest and runs
    // where the compiler does exist.
    //
    // Linked against kernel/user/libc, which is the whole point: the program
    // reaches nothing but write, brk and exit.
    const c_flags = [_][]const u8{
        "-ffreestanding",
        // Without this the compiler is free to turn printf("...\n") into
        // puts, and printf is one of the things under test.
        "-fno-builtin",
        "-O2",
        "-w",
    };
    const demo_prog = b.addExecutable(.{
        .name = "clarity-demo",
        .root_source_file = null,
        .target = user_target,
        .optimize = .ReleaseSmall,
    });
    demo_prog.addIncludePath(b.path("user/libc/include"));
    demo_prog.addCSourceFile(.{ .file = b.path("user/clarity_demo.c"), .flags = &c_flags });
    demo_prog.addCSourceFiles(.{
        .root = b.path("user/libc/src"),
        .files = &.{
            "bignum.c", "ctype.c",  "dtoa.c",   "malloc.c", "math.c",
            "printf.c", "qsort.c",  "stdlib.c", "string.c", "strtod.c",
            "sys.c",
        },
        .flags = &c_flags,
    });
    demo_prog.addAssemblyFile(b.path("user/libc/src/setjmp.S"));
    demo_prog.addAssemblyFile(b.path("user/libc/src/start.S"));
    demo_prog.setLinkerScript(b.path("user/user.ld"));
    demo_prog.entry = .{ .symbol_name = "_start" };
    demo_prog.pie = false;

    kernel.root_module.addAnonymousImport("demo_elf", .{
        .root_source_file = demo_prog.getEmittedBin(),
    });

    b.installArtifact(kernel);

    // `zig build run` — boot the kernel under QEMU.
    //
    // Through a script rather than a direct QEMU invocation, because QEMU
    // cannot boot this image with `-kernel`: it is multiboot2, and `-kernel`
    // on x86 wants a bzImage or an ELF with a PVH note. It used to try
    // anyway, and every `zig build run` ended in
    //
    //   Error loading uncompressed kernel without PVH ELF Note
    //
    // with nothing on the serial line. The script builds the same GRUB rescue
    // ISO the boot gate builds, so `zig build run` and CI boot the same way.
    const qemu = b.addSystemCommand(&.{"sh"});
    qemu.addFileArg(b.path("tools/run_x86.sh"));
    qemu.addArtifactArg(kernel);

    const run_step = b.step("run", "Boot the x86-64 kernel under QEMU (builds a GRUB ISO)");
    run_step.dependOn(&qemu.step);

    // ── AArch64 (Apple-Silicon-class) kernel ──────────────
    //
    // Built under its own step (`zig build aarch64`) rather than the
    // default install, so the x86_64 build and its boot gate are wholly
    // unaffected. QEMU's `virt` machine is the CI target.
    const aarch64_target = b.resolveTargetQuery(.{
        .cpu_arch = .aarch64,
        .os_tag = .freestanding,
        .abi = .none,
    });

    const kernel_arm = b.addExecutable(.{
        .name = "clarity-kernel-aarch64",
        .root_source_file = b.path("main_aarch64.zig"),
        .target = aarch64_target,
        .optimize = optimize,
    });
    kernel_arm.setLinkerScript(b.path("boot/linker_aarch64.ld"));
    kernel_arm.addAssemblyFile(b.path("arch/aarch64/boot.S"));
    kernel_arm.addAssemblyFile(b.path("arch/aarch64/vectors.S"));
    kernel_arm.addAssemblyFile(b.path("arch/aarch64/user.S"));
    kernel_arm.addAssemblyFile(b.path("arch/aarch64/context.S"));
    kernel_arm.entry = .{ .symbol_name = "_start" };

    // The bootable artefact is the flat binary, not the ELF.
    //
    // A bootloader following the ARM64 Linux boot protocol reads the header
    // at offset 0 of a raw image; handed an ELF instead, QEMU jumps to the
    // entry point and loads no device tree, so the kernel has no way to learn
    // what machine it is on. The ELF is still installed alongside it, because
    // it carries the symbols a debugger and a disassembler need.
    const kernel_arm_bin = b.addObjCopy(kernel_arm.getEmittedBin(), .{ .format = .bin });
    const install_arm_bin = b.addInstallBinFile(
        kernel_arm_bin.getOutput(),
        "clarity-kernel-aarch64.img",
    );

    const aarch64_step = b.step("aarch64", "Build the AArch64 kernel");
    aarch64_step.dependOn(&b.addInstallArtifact(kernel_arm, .{}).step);
    aarch64_step.dependOn(&install_arm_bin.step);

    // `zig build run-aarch64`. This one QEMU really can boot with `-kernel`:
    // the image carries an ARM64 Linux Image header, which is the format
    // `-kernel` expects on this architecture — and following that protocol is
    // also what gets the kernel handed a device tree.
    const qemu_arm = b.addSystemCommand(&.{
        "qemu-system-aarch64",
        "-M",         "virt",
        "-cpu",       "cortex-a72",
        "-m",         "512",
        "-device",    "ramfb",
        "-serial",    "stdio",
        "-no-reboot",
        "-kernel",
    });
    qemu_arm.addFileArg(kernel_arm_bin.getOutput());
    qemu_arm.step.dependOn(aarch64_step);

    const run_arm_step = b.step("run-aarch64", "Boot the AArch64 kernel under QEMU");
    run_arm_step.dependOn(&qemu_arm.step);
}
