#!/usr/bin/env python3
"""Turn tools/font8x8.txt into graphics/font8x8.zig, and into a picture.

The Zig file is checked in, so building the kernel needs no Python. This
script is how it is regenerated, and — with --png — how the result is
checked: eight bytes per glyph is not something anyone can read, so the
verification is to draw the font back out and look at it.

    python3 tools/make_font.py                    # rewrite graphics/font8x8.zig
    python3 tools/make_font.py --png atlas.png    # and draw it
    python3 tools/make_font.py --check            # fail if the .zig is stale
"""
import sys, os, re

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "font8x8.txt")
OUT = os.path.join(HERE, "..", "graphics", "font8x8.zig")

FIRST, LAST = 32, 126


def parse():
    """Read the glyph source. Returns {codepoint: [8 rows of 8 bools]}."""
    glyphs = {}
    code = None
    rows = []
    with open(SRC) as f:
        for lineno, raw in enumerate(f, 1):
            line = raw.rstrip("\n")
            # A comment only outside a glyph. Inside one, a line beginning
            # with '#' is a row whose leftmost pixel is lit — which is how
            # this first went wrong: the '#' glyph's own rows were read as
            # comments and it came out six rows tall.
            if code is None and line.startswith("#"):
                continue
            header = re.match(r"^(\d+) ", line) if code is None else None
            if header:
                if code is not None:
                    raise SystemExit(f"{SRC}:{lineno}: glyph {code} has "
                                     f"{len(rows)} rows, wanted 8")
                code = int(header.group(1))
                rows = []
                continue
            if code is None:
                if line.strip():
                    raise SystemExit(f"{SRC}:{lineno}: stray text {line!r}")
                continue
            if not line.strip():
                continue
            if len(line) != 8 or set(line) - set(".#"):
                raise SystemExit(f"{SRC}:{lineno}: row {line!r} is not eight "
                                 f"of '.' and '#'")
            rows.append([c == "#" for c in line])
            if len(rows) == 8:
                if code in glyphs:
                    raise SystemExit(f"{SRC}:{lineno}: glyph {code} twice")
                glyphs[code] = rows
                code = None
    if code is not None:
        raise SystemExit(f"{SRC}: glyph {code} ended with {len(rows)} rows")

    missing = [c for c in range(FIRST, LAST + 1) if c not in glyphs]
    if missing:
        raise SystemExit(f"{SRC}: no glyph for {missing}")
    extra = [c for c in glyphs if not FIRST <= c <= LAST]
    if extra:
        raise SystemExit(f"{SRC}: glyph outside {FIRST}..{LAST}: {extra}")
    return glyphs


def to_zig(glyphs):
    """One byte per row, bit 7 leftmost — so a row draws by shifting left."""
    lines = [
        "//! The console font: 8x8, ASCII 32..126.",
        "//!",
        "//! Generated by tools/make_font.py from tools/font8x8.txt. Edit the",
        "//! text file, not this one — and run the generator with --png",
        "//! afterwards, because eight bytes per glyph is not something anyone",
        "//! can proofread. `zig build` does not need Python; this file is",
        "//! checked in.",
        "//!",
        "//! Authored rather than converted from an existing font, so the",
        "//! kernel carries no third-party font licence.",
        "//!",
        "//! One byte per row, bit 7 leftmost, so drawing a row is a shift and",
        "//! a test rather than a lookup.",
        "",
        "pub const WIDTH: usize = 8;",
        "pub const HEIGHT: usize = 8;",
        "pub const FIRST: u8 = 32;",
        "pub const LAST: u8 = 126;",
        "",
        "/// The glyph for `c`, or the one for '?' if it is outside the range —",
        "/// so an unprintable byte shows as something rather than reading off",
        "/// the end of the table.",
        "pub fn glyph(c: u8) *const [HEIGHT]u8 {",
        "    if (c < FIRST or c > LAST) return &GLYPHS['?' - FIRST];",
        "    return &GLYPHS[c - FIRST];",
        "}",
        "",
        "const GLYPHS = [_][HEIGHT]u8{",
    ]
    for code in range(FIRST, LAST + 1):
        rows = glyphs[code]
        bytes_ = []
        for r in rows:
            v = 0
            for x, on in enumerate(r):
                if on:
                    v |= 0x80 >> x
            bytes_.append(f"0x{v:02X}")
        ch = chr(code)
        label = "space" if ch == " " else ("'" + ch + "'" if ch != "'" else "quote")
        lines.append("    // %-3d %s" % (code, label))
        lines.append("    .{ " + ", ".join(bytes_) + " },")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def draw(glyphs, path):
    from PIL import Image
    cols, scale, pad = 16, 6, 2
    rows_n = (LAST - FIRST + cols) // cols
    cell_w, cell_h = 8 * scale + pad, 8 * scale + pad
    img = Image.new("RGB", (cols * cell_w, rows_n * cell_h), (16, 24, 32))
    px = img.load()
    for i, code in enumerate(range(FIRST, LAST + 1)):
        gx, gy = (i % cols) * cell_w, (i // cols) * cell_h
        for y, row in enumerate(glyphs[code]):
            for x, on in enumerate(row):
                if not on:
                    continue
                for dy in range(scale):
                    for dx in range(scale):
                        px[gx + x * scale + dx, gy + y * scale + dy] = (230, 240, 250)
    img.save(path)
    print(f"wrote {path} ({img.width}x{img.height})")


def main():
    glyphs = parse()
    text = to_zig(glyphs)
    out = os.path.normpath(OUT)

    if "--check" in sys.argv:
        have = open(out).read() if os.path.exists(out) else None
        if have != text:
            raise SystemExit(f"{out} is stale; run tools/make_font.py")
        print(f"{out} is up to date ({LAST - FIRST + 1} glyphs)")
    else:
        with open(out, "w") as f:
            f.write(text)
        print(f"wrote {out} ({LAST - FIRST + 1} glyphs)")

    if "--png" in sys.argv:
        draw(glyphs, sys.argv[sys.argv.index("--png") + 1])


main()
