#!/usr/bin/env python3
"""Offline font-atlas rasterizer for KyanOS.

Rasterizes printable ASCII (codepoints 32..126) from a real TTF at a small
ramp of pixel sizes, capturing each glyph's anti-aliased grayscale coverage
plus its metrics (advance, left bearing, baseline-to-top). Emits a Clarity
data module (`stdlib/font_atlas.clarity`) whose `atlas_data()` returns:

    {
      "sizes": [15, 20, 30, 44],
      "ascent": {"15": .., "20": .., ...},
      "glyphs": {
        "15": { "65": {"w":..,"h":..,"adv":..,"left":..,"top":..,"cov":"<b64>"}, ... },
        ...
      }
    }

Coverage is stored as a base64 string. Because the Clarity runtime's
`decode64` round-trips bytes through UTF-8 (which mangles bytes > 127), the
8-bit coverage is quantized to 7 bits (0..127) before encoding, so every
decoded byte is a clean single-byte ASCII codepoint recoverable via
`char_code(char_at(s, i))`. The renderer scales the value back up (×2).
"""

import base64
import os
import sys

from PIL import ImageFont, Image

FONT_CANDIDATES = [
    "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
]

SIZES = [15, 20, 30, 44]
FIRST_CP = 32
LAST_CP = 126


def pick_font_path():
    for p in FONT_CANDIDATES:
        if os.path.exists(p):
            return p
    raise SystemExit("No usable TTF found among: " + ", ".join(FONT_CANDIDATES))


def quantize_cov(data):
    """8-bit grayscale coverage -> 7-bit-safe bytes (0..127)."""
    return bytes((c >> 1) for c in data)


def build():
    font_path = pick_font_path()
    sizes_glyphs = {}
    ascent_map = {}

    for size in SIZES:
        font = ImageFont.truetype(font_path, size)
        ascent, _descent = font.getmetrics()
        ascent_map[str(size)] = ascent
        glyphs = {}
        for cp in range(FIRST_CP, LAST_CP + 1):
            ch = chr(cp)
            adv = int(round(font.getlength(ch)))
            mask, (off_x, off_y) = font.getmask2(ch)
            w, h = mask.size
            if w == 0 or h == 0:
                glyphs[str(cp)] = {
                    "w": 0, "h": 0, "adv": adv,
                    "left": int(off_x), "top": ascent - int(off_y), "cov": "",
                }
                continue
            img = Image.frombytes("L", (w, h), bytes(mask))
            cov = quantize_cov(img.tobytes())
            b64 = base64.b64encode(cov).decode("ascii")
            glyphs[str(cp)] = {
                "w": w, "h": h, "adv": adv,
                "left": int(off_x),
                "top": ascent - int(off_y),   # baseline -> top of bitmap
                "cov": b64,
            }
        sizes_glyphs[str(size)] = glyphs

    return font_path, ascent_map, sizes_glyphs


def emit_clarity(font_path, ascent_map, sizes_glyphs):
    out = []
    out.append("-- font_atlas.clarity — GENERATED by tools/gen_font_atlas.py. DO NOT EDIT.")
    out.append("--")
    out.append("-- Anti-aliased proportional font atlas rasterized offline from a real")
    out.append("-- TTF (" + os.path.basename(font_path) + ") at pixel sizes " + str(SIZES) + ".")
    out.append("-- Each glyph's grayscale AA coverage is a base64 string of 7-bit-safe")
    out.append("-- bytes (0..127); atlas_font.clarity decodes it via decode64 and scales")
    out.append("-- the value back to 0..255. Metrics: w,h (bitmap), adv (advance),")
    out.append("-- left (x bearing), top (baseline->bitmap top). ascent positions by top-left.")
    out.append("")
    out.append("fn atlas_data() {")
    out.append("    return {")

    # sizes list
    out.append('        "sizes": [' + ", ".join(str(s) for s in SIZES) + "],")

    # ascent map
    asc_parts = ", ".join('"' + k + '": ' + str(ascent_map[k]) for k in [str(s) for s in SIZES])
    out.append('        "ascent": {' + asc_parts + "},")

    # glyphs
    out.append('        "glyphs": {')
    size_keys = [str(s) for s in SIZES]
    for si, sk in enumerate(size_keys):
        out.append('            "' + sk + '": {')
        glyphs = sizes_glyphs[sk]
        cp_keys = [str(cp) for cp in range(FIRST_CP, LAST_CP + 1)]
        for ci, ck in enumerate(cp_keys):
            g = glyphs[ck]
            comma = "," if ci < len(cp_keys) - 1 else ""
            out.append(
                '                "' + ck + '": {"w":' + str(g["w"])
                + ',"h":' + str(g["h"]) + ',"adv":' + str(g["adv"])
                + ',"left":' + str(g["left"]) + ',"top":' + str(g["top"])
                + ',"cov":"' + g["cov"] + '"}' + comma
            )
        out.append("            }" + ("," if si < len(size_keys) - 1 else ""))
    out.append("        }")
    out.append("    }")
    out.append("}")
    out.append("")
    return "\n".join(out)


def main():
    font_path, ascent_map, sizes_glyphs = build()
    text = emit_clarity(font_path, ascent_map, sizes_glyphs)
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out_path = os.path.join(root, "stdlib", "font_atlas.clarity")
    with open(out_path, "w") as f:
        f.write(text)
    size_kb = len(text) / 1024.0
    print("font: " + font_path)
    print("sizes: " + str(SIZES))
    print("wrote " + out_path + " (" + ("%.1f" % size_kb) + " KB)")


if __name__ == "__main__":
    main()
